# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.enableLutRouteBelPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.BramSDPPropagationFix 1
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA/ITA.cache/wt [current_project]
set_property parent.project_path /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA/ITA.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu106:part0:2.4 [current_project]
set_property ip_output_repo /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA/ITA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA/ITA.srcs/sources_1/imports/common_cells/assertions.svh
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/hci-master/rtl/common/hci_helpers.svh
}
set_property file_type "Verilog Header" [get_files /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA/ITA.srcs/sources_1/imports/common_cells/assertions.svh]
set_property file_type "Verilog Header" [get_files /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/hci-master/rtl/common/hci_helpers.svh]
read_verilog -library xil_defaultlib -sv {
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/common_cells/src/cf_math_pkg.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/common_cells/src/fifo_v3.sv
  /tmp/mnt_ryloth_ipek/shared/hwpe-stream/rtl/hwpe_stream_package.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/hci-master/rtl/common/hci_package.sv
  /tmp/mnt_ryloth_ipek/shared/hci/rtl/core/hci_core_assign.sv
  /tmp/mnt_ryloth_ipek/shared/hci/rtl/core/hci_core_fifo.sv
  /tmp/mnt_ryloth_ipek/shared/hci/rtl/core/hci_core_mux_ooo.sv
  /tmp/mnt_ryloth_ipek/shared/hci/rtl/core/hci_core_r_id_filter.sv
  /tmp/mnt_ryloth_ipek/shared/hci/rtl/core/hci_core_sink.sv
  /tmp/mnt_ryloth_ipek/shared/hci/rtl/core/hci_core_source.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/hci-master/rtl/common/hci_interfaces.sv
  /tmp/mnt_ryloth_ipek/shared/hwpe-ctrl/rtl/hwpe_ctrl_package.sv
  /tmp/mnt_ryloth_ipek/shared/hwpe-ctrl/rtl/hwpe_ctrl_interfaces.sv
  /tmp/mnt_ryloth_ipek/shared/hwpe-ctrl/rtl/hwpe_ctrl_regfile.sv
  /tmp/mnt_ryloth_ipek/shared/hwpe-ctrl/rtl/hwpe_ctrl_regfile_ff.sv
  /tmp/mnt_ryloth_ipek/shared/hwpe-ctrl/rtl/hwpe_ctrl_regfile_latch.sv
  /tmp/mnt_ryloth_ipek/shared/hwpe-ctrl/rtl/hwpe_ctrl_regfile_latch_test_wrap.sv
  /tmp/mnt_ryloth_ipek/shared/hwpe-ctrl/rtl/hwpe_ctrl_slave.sv
  /tmp/mnt_ryloth_ipek/shared/hwpe-stream/rtl/streamer/hwpe_stream_addressgen_v3.sv
  /tmp/mnt_ryloth_ipek/shared/hwpe-stream/rtl/basic/hwpe_stream_assign.sv
  /tmp/mnt_ryloth_ipek/shared/hwpe-stream/rtl/basic/hwpe_stream_fence.sv
  /tmp/mnt_ryloth_ipek/shared/hwpe-stream/rtl/fifo/hwpe_stream_fifo.sv
  /tmp/mnt_ryloth_ipek/shared/hwpe-stream/rtl/fifo/hwpe_stream_fifo_passthrough.sv
  /tmp/mnt_ryloth_ipek/shared/hwpe-stream/rtl/fifo/hwpe_stream_fifo_scm.sv
  /tmp/mnt_ryloth_ipek/shared/hwpe-stream/rtl/fifo/hwpe_stream_fifo_scm_test_wrap.sv
  /tmp/mnt_ryloth_ipek/shared/hwpe-stream/rtl/hwpe_stream_interfaces.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_package.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_accumulator.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_activation.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_controller.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_dotp.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_fifo_controller.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_gelu.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/hwpe/ita_hwpe_package.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/hwpe/ita_hwpe_ctrl.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/hwpe/ita_hwpe_engine.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/hwpe/ita_hwpe_input_bias_buffer.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/hwpe/ita_hwpe_input_bias_fence.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/hwpe/ita_hwpe_input_buffer.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/hwpe/ita_hwpe_output_buffer.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/hwpe/ita_hwpe_streamer.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_inp1_mux.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_inp2_mux.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_input_sampler.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_max_finder.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_output_controller.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_register_file_1w_1r_double_width_write.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_register_file_1w_multi_port_read.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_register_file_1w_multi_port_read_we.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_relu.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_requantization_controller.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_requantizer.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_serdiv.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_softmax.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_softmax_top.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_sumdotp.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/ita_weight_controller.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/common_cells/src/lzc.sv
  /tmp/mnt_ryloth_ipek/shared/scm/fpga_scm/register_file_1r_1w.sv
  /tmp/mnt_ryloth_ipek/shared/scm/fpga_scm/register_file_1r_1w_1row.sv
  /tmp/mnt_ryloth_ipek/shared/scm/fpga_scm/register_file_1w_multi_port_read.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/tech_cells_generic/src/fpga/tc_clk_xilinx.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/tech_cells_generic/src/fpga/tc_sram_xilinx.sv
  /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA-BIC/src/hwpe/ita_hwpe_top.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA/ITA.srcs/constrs_1/new/synthesis_wo_contsraints.xdc
set_property used_in_implementation false [get_files /tmp/mnt_ryloth_ipek/vivado_projects/ITA_Project/ITA/ITA.srcs/constrs_1/new/synthesis_wo_contsraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ita_hwpe_top -part xczu7ev-ffvc1156-2-e -mode out_of_context


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ita_hwpe_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ita_hwpe_top_utilization_synth.rpt -pb ita_hwpe_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
