# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /nas/ei/home/ge27lob/Desktop/ITA_Pulp/ITA_Pulp.cache/wt [current_project]
set_property parent.project_path /nas/ei/home/ge27lob/Desktop/ITA_Pulp/ITA_Pulp.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu106:part0:2.4 [current_project]
set_property ip_output_repo /nas/ei/home/ge27lob/Desktop/ITA_Pulp/ITA_Pulp.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog /nas/ei/home/ge27lob/Desktop/ITA_Pulp/common_cells/include/common_cells/assertions.svh
set_property file_type "Verilog Header" [get_files /nas/ei/home/ge27lob/Desktop/ITA_Pulp/common_cells/include/common_cells/assertions.svh]
read_verilog -library xil_defaultlib -sv {
  /nas/ei/home/ge27lob/Desktop/ITA_Pulp/ITA_Pulp.srcs/sources_1/new/cf_math_pkg.sv
  /nas/ei/home/ge27lob/Desktop/ITA_Pulp/common_cells/src/cf_math_pkg.sv
  /nas/ei/home/ge27lob/Desktop/ITA_Pulp/common_cells/src/fifo_v3.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_package.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_accumulator.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_activation.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_controller.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_dotp.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_fifo_controller.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_gelu.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_inp1_mux.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_inp2_mux.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_input_sampler.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_max_finder.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_output_controller.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_register_file_1w_multi_port_read.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_register_file_1w_multi_port_read_we.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_relu.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_requantization_controller.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_requantizer.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_serdiv.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_softmax.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_softmax_top.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_sumdotp.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita_weight_controller.sv
  /nas/ei/home/ge27lob/Desktop/ITA_Pulp/common_cells/src/lzc.sv
  /nas/ei/home/ge27lob/Desktop/ITA_Pulp/ITA_Pulp.srcs/sources_1/new/tc_clk_xilinx.sv
  /nas/ei/home/ge27lob/Desktop/ITA_Pulp/ITA_Pulp.srcs/sources_1/new/tc_sram.sv
  /nas/ei/home/ge27lob/Desktop/ITA/src/ita.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ita -part xczu7ev-ffvc1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ita.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ita_utilization_synth.rpt -pb ita_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
